### ISSUE TITLE
Feature request: ability to keep temporary files

### ISSUE THREAD

**Issue by fgsch** [dobin/ffw#18]
It'd be nice if generated files could be kept via some option (e.g. `keep_temp: True`).
What do you think?

**Comment by y1026** [comment]
Hello,

I think we should think of an efficient way.

Because the capacity of the disk is filling up quickly.

Thanks.

**Comment by dobin** [comment]
I once had 2 million files in the out/ directory, because of 1 million crashes. It can get big pretty fast. 

I usually have 30 executions per second per thread, on my 32 core machine around 128 threads, therefore like 13,8gb of data in one hour (assuming 1kb per file). 

But it's simple to add the flag, maybe for debugging purposes. Check it here: https://github.com/dobin/ffw/blob/master/fuzzer/fuzzingiterationdata.py#L112

**Comment by fgsch** [comment]
Yeah, that's what I've been using. I've opened a PR.

**Comment by dobin** [comment]
Thanks!
